use rubocop for linting. ran safe autocorrect
getkuby/kuby-core pull request #16
Opened 2020-10-02 17:51 UTC by jdoconnor

if this is of interest, I found a lot of ruby style convention updates. 

I intentionally created a config with violations that appeared to be intentional as to not rewrite developer intention.

2020-10-08 20:04 UTC, jdoconnor commented
@camertron

2020-10-12 00:05 UTC, camertron requested changes
Thanks for doing this :) Def not a fan of all the things rubocop does, but this is a great start.

2020-10-12 00:05 UTC, camertron commented on lib/kuby/environment.rb
> +    alias configured? configured
Let's keep `alias_method`, it's a lot more flexible than `alias`, can be overridden, etc.

2020-10-12 00:05 UTC, camertron commented on lib/kuby/kubernetes/deployer.rb
> +            deployed_image = deployment.dig('spec', 'template', 'spec', 'containers', 0, 'image')
Huh. Why does rubocop like `%w(a b c)` but not `dig(*%w(a b c))`??

2020-10-12 00:05 UTC, camertron commented on lib/kuby/plugins/nginx_ingress.rb
> +        false
Are you sure these are equivalent?

2020-10-13 00:50 UTC, jdoconnor commented on lib/kuby.rb
> +      raise MissingConfigError, "couldn't find Kuby config file at #{config_file}" unless File.exist?(config_file)
should be. I'll take a look

2020-10-13 00:52 UTC, jdoconnor commented on lib/kuby/plugins/nginx_ingress.rb
> +        false
should be. that's the end of a method

2023-05-06 14:59 UTC, jdoconnor commented
out of date. closing

2023-05-06 14:59 UTC, closed without merging