Add docker build args support and image filtering
getkuby/kuby-core pull request #65
Opened 2021-11-24 16:29 UTC by palkan

This PR enhance `kuby build` functionality:
- Allows adding additional (arbitrary) args to `docker build`
- Adds identifiers to images and `--only` flag to build only the selected image.

Why?

Here is my example use case—faster deploys on GitHub Actions:

```yml
- name: Build and push Docker images
   run: |
     bundle exec kuby -e production build --only app --    --cache-from=type=gha,scope=app --cache-to=type=gha,scope=app,mode=max --push
     bundle exec kuby -e production build --only assets -- --cache-from=type=gha,scope=assets --cache-to=type=gha,scope=assets,mode=max --push
```

First, we need to make it possible to specify `--cache-from` and `--cache-to` options. That's why I added `args` support.

Then, for this particular use case, we need to use different cache names for different images (otherwise the last one wins, or overwrites the cache, making it useless).

_"Maybe, you should use plain `docker build` then?"_

Nope. Kuby takes care of build args and all other stuff I don't want to think about 🙂

2021-11-24 21:51 UTC, camertron requested changes
Nice, this looks really cool! Just a few small adjustments necessary and then I'd be happy to merge :)

2021-11-24 21:51 UTC, camertron commented on docs/docs/customizing_docker_build.md
> +## Docker build options
It would be great to mention the new `--only` flag in here somewhere 😄

2021-11-24 21:51 UTC, camertron commented on lib/kuby/commands.rb
> +        tasks.build(build_args, args, options[:only])
I'm concerned about the ambiguity of the name `args` here and elsewhere in the call stack. What would you think about `docker_args` instead?

2021-11-26 21:09 UTC, camertron approved these changes
Almost there!

2021-11-26 21:09 UTC, camertron commented on docs/docs/customizing_docker_build.md
> +**NOTE:** You should take care of adding `ARG SOURCE_COMMIT` and `ENV SOURCE_COMMIT=$SOURCE_COMMIT` yourself (see above).
```suggestion
**NOTE:** You will need to add `ARG SOURCE_COMMIT` and `ENV SOURCE_COMMIT=$SOURCE_COMMIT` to the Dockerfile yourself (see above).
```

2021-11-28 17:43 UTC, merged

2021-11-28 17:44 UTC, camertron commented
Will release this afternoon 😁

2021-11-28 22:31 UTC, camertron commented
Published in v0.14.0.

2021-11-29 09:08 UTC, palkan commented
Awesome! Thanks!